### ISSUE TITLE
[Question] render instead of render_to_response in Chapter 4?

### ISSUE THREAD

**Issue by esacteksab** [askedrelic/django-book#2]
https://github.com/esacteksab/django-book/blob/master/en/chapter04.rst

Chapter 4 mentions render_to_response, but doesn't mention RequestContext in the render_to_response

New in 1.3 (isn't this book only up to 1.2?) is render, a shortcut (and IMO is awesome!)

https://docs.djangoproject.com/en/1.4/topics/http/shortcuts/

Not knowing the targeted audience, intended purpose, etc. etc. I don't know if you want to expose short cuts or if there is a reason/want/desire to do it the "old" way?

**Comment by askedrelic** [comment]
Do you mean further down, around here? http://django-book.readthedocs.org/en/latest/chapter04.html#render-to-response

I think that would make more sense to push render over render_to_response. I swear I remember reading arguments pushing render because it's cleaner vs the legacy shortcut that is render_to_response.

Overall with the project, I'm trying to get some more goals or intent messages going, but I think your experience should be the main factor guiding messaging. Generally, I feel like render is promoted more and worth pushing to new users.
